/////////////////////////////////////////////////////////// 
//  Items.cs
//  Implementation of the Class Items
//  Generated by Gazmend Mehmeti
//  Created on:      18.05.09 1:43:17 PM
//  Original author: Gazmend Mehmeti
///////////////////////////////////////////////////////////

using FinabitAPI.Core.Global.dto;
using System;
using System.Collections.Generic;
using System.Text;

namespace FinabitAPI.Finabit.Items.dto
{
    public class ItemsLookup : BaseClass
    {

        #region Class_Methods


        public ItemsLookup()
        {
         Taxable = false;
         SalesPrice = 0;
         CostPrice =0;
         ViewPOS =false;
         PreferedItem = false;
         Color ="";
         UnitDescription  ="";
         LocationID = 0;
         ItemGroup  ="";
         Quantity = 0;
         ItemType  ="";
         ItemGroupID = 0;
         Favorite = false;
         LocationName  ="";
         PDAItemName  ="";
         DepartmentID = 0;
         DoganaValue = 0;
         VATValue = 0;
         AkcizaValue = 0;
         DueDate = DateTime.Now;
         BarcodeHasQuantity= false; 
         Coefficient = 0;
         UnitID = 0;
         UnitName  ="";
         Barcode  ="";
         ID1 = 0;
         Coefficient2 = 0;
         SalesPrice2 = 0;
         Discount = 0;
         LastBuyPrice = 0;
         LastBuyRabat = 0;
         FromTime = "";
         ToTime = "";
        }
        /// <summary>
        /// The ItemID field in the DB
        /// </summary>
        public string ItemID
        {
            get;
            set;
        }

        /// <summary>
        /// The ItemName field in the DB
        /// </summary>
        public string ItemName
        {
            get;
            set;
        }

        /// <summary>
        /// The Dogana field in the DB
        /// </summary>
        public bool Dogana
        {
            get;
            set;
        }

        public bool Akciza
        {
            get;
            set;
        } 

        #endregion

        public bool Taxable { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal CostPrice { get; set; }
        public bool ViewPOS { get; set; }
        public bool PreferedItem { get; set; }
        public string Color { get; set; }

        public string UnitDescription { get; set; }
        public int LocationID { get; set; }
        public string ItemGroup { get; set; }
        public decimal Quantity { get; set; }
        public string ItemType { get; set; }
        public int ItemGroupID { get; set; }
        public bool Favorite { get; set; }
        public string LocationName { get; set; }

        public string PDAItemName { get; set; }

        public int DepartmentID { get; set; }

        public decimal DoganaValue { get; set; }
        public decimal VATValue { get; set; }
        public decimal AkcizaValue { get; set; }
        public DateTime DueDate { get; set; }
        public bool BarcodeHasQuantity { get; set; }

        public decimal Coefficient { get; set; }
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public string Barcode { get; set; }
        public int ID1 { get; set; }
        public decimal Coefficient2 { get; set; }
        public decimal SalesPrice2 { get; set; }
        public decimal Discount { get; set; }
        public decimal LastBuyPrice { get; set; }
        public decimal LastBuyRabat { get; set; }
        public int SubOrderID { get; set; }
        public int LocationID2 { get; set; }
        public bool HasAttributes { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public decimal SalesPrice3 { get; set; }



       
        public decimal LastBuyRabat2 { get; set; }
        public int LastStockLocation { get; set; }
        public decimal CmimiOrigjinal { get; set; }
        public string Aksion { get; set; }
        public bool Unit1Default { get; set; }
        public int ORD { get; set; }

        public decimal GroupVipValue { get; set; }
        public int ItemAttributeLocation { get; set; }
        public decimal Weight { get; set; }
        public decimal VATPrice { get; set; }
        public string AccountCode { get; set; }
        public string PLU { get; set; }
        public bool IsService { get; set; }
      
        public decimal SalesPrice_Old { get; set; }
        public decimal SalesPrice2_Old { get; set; }
        public bool IsInAction { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public decimal Discount2 { get; set; }
        public decimal MinimalPrice { get; set; }
        public string Origin { get; set; }
        public int PriceMenuID { get; set; }
        public string Barcode_N { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomField6 { get; set; }
        public decimal Discount3 { get; set; }
        public int Maximum { get; set; }
        public string DepartmentName { get; set; }
        public int ItemTypeID { get; set; }
        public bool Active { get; set; }
        public string MaximumQuantity { get; set; }
        public string Barcode1 { get; set; }
        public string Barcode2 { get; set; }
        public string Category { get; set; }
        public string ItemTemplate { get; set; }
        public string Barcode3 { get; set; }
        public decimal MaxDiscount { get; set; }
        //fg
        public decimal NettoBruttoWeight { get; set; }
        public decimal BrutoWeight { get; set; }
        //--
        public string Prodhuesi { get; set; }

        public int ShifraProdhuesi { get; set; }

    }
}