namespace FinabitAPI.Models
{
    public class TransactionDetail
    {
        public int ID { get; set; }
        public int TransactionID { get; set; }
        public int DetailsType { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string Account { get; set; }
        public decimal CostPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal PriceWithDiscount { get; set; }
        public decimal Value { get; set; }
        public int PaymentID { get; set; }
        public decimal PaymentValue { get; set; }
        public decimal PurchasedValue { get; set; }
        public decimal StockQuantity { get; set; }
        public string ItemTransferFrom { get; set; }
        public int InsBy { get; set; }
        public DateTime InsDate { get; set; }
        public int LUB { get; set; }
        public int LUN { get; set; }
        public DateTime LUD { get; set; }
        public int UnitID { get; set; }
        public decimal Coefficient { get; set; }
        public string Barcode { get; set; }
        public string UnitName { get; set; }
        public decimal VATValue { get; set; }
        public int StockLocationID { get; set; }
        public string StockLocationName { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal SalesPrice2 { get; set; }
        public decimal SalesPrice3 { get; set; }
        public decimal VATPrice { get; set; }
        public decimal OriginVATPrice { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal IM7Price { get; set; }
        public decimal OverValue { get; set; }
        public decimal DoganaValue { get; set; }
        public decimal VATPercent { get; set; }
        public decimal AkcizaValue { get; set; }
        public int ArticleID { get; set; }
        public string ItemUnitName { get; set; }
        public DateTime ExpirationDate { get; set; }
        public int CompensationID { get; set; }
        public string PDAItemName { get; set; }
        public decimal Marzhina { get; set; }
        public decimal PriceFactor { get; set; }
        public decimal InvoiceValue { get; set; }
        public int ItemType { get; set; }
        public string AccountCode { get; set; }
        public decimal PriceWithoutVATUse { get; set; }
        public decimal ItemCoef_Quantity { get; set; }
        public int SubOrderID { get; set; }
        public int AssetID { get; set; }
        public bool IsService { get; set; }
        public int IsInAction { get; set; }
        public int SubOrderReceived { get; set; }
        public decimal Dim_1 { get; set; }
        public decimal Dim_2 { get; set; }
        public decimal Dim_3 { get; set; }
        public int DepartmentID { get; set; }
        public int RowOrder { get; set; }
        public string SerialNumber { get; set; }
        public DateTime GuaranteeDate { get; set; }
        public int POSProductionItemID { get; set; }
        public DateTime TransactionDate { get; set; }
        public string PositionNumber { get; set; }
        public string PLU { get; set; }
        public int TargetPlanID { get; set; }
        public decimal VATPriceWithOutRABAT { get; set; }
        public decimal AllValueWithOutRabat { get; set; }
        public string Memo { get; set; }
        public decimal MinimalPrice { get; set; }
        public string Origin { get; set; }
        public string ProductionSerialaNumber { get; set; }
        public decimal Quantity_Lot { get; set; }
        public decimal KM { get; set; }
        public int RBOOKID { get; set; }
        public int PriceMenuID { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public decimal TaxAtSource { get; set; }
        public decimal Coefficient4 { get; set; }
        public decimal RABAT2 { get; set; }
        public decimal RABAT3 { get; set; }
        public decimal Maximum { get; set; }
        public string CustomField3 { get; set; }
        public string Barcode2 { get; set; }
        public string ProjectName { get; set; }
        public decimal QuantityBruto { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomField6 { get; set; }
        public string Memo2 { get; set; }
        public decimal NettoBruttoWeight { get; set; }
        public decimal BrutoWeight { get; set; }
        public decimal NumriPaletave { get; set; }
        public decimal PeshaPaletes { get; set; }
        public decimal PeshaKartonit { get; set; }
        public string PlateNo { get; set; }
        public string TermsOfDelivery { get; set; }
        public string CommodityCode { get; set; }
        public string DeliveryMethod { get; set; }
        public string ShipmentTerms { get; set; }
        public string CustOrderNo { get; set; }
        public string Address { get; set; }
        public string ShippAddress { get; set; }
        public string Reference { get; set; }
        public string SealNo { get; set; }
        public string ProductionSerialNumber_Det { get; set; }
        public DateTime ExpirationDate_Det { get; set; }
        public decimal VleraPaTVSH18 { get; set; }
        public decimal VleraPaTVSH8 { get; set; }
        public string Prodhuesi { get; set; }
        public string ItemGroup { get; set; }
    }
}
