/////////////////////////////////////////////////////////// 
//  TransactionsDetails.cs
//  Implementation of the Class TransactionsDetails
//  Generated by Gazmend Mehmeti
//  Created on:      07.05.09 7:32:25 PM
//  Original author: Gazmend Mehmeti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Linq;



namespace Finabit_API.Models
{
    public class TransactionsDetails : BaseClass
    {
        public TransactionsDetails()
        {
            TransactionID = 0;
            DetailsType = 0;
            ItemID = "";
            ItemName = "";
            Account = "";
            Contracts = "";
            Quantity = 0;
            Price = 0;
            CostPrice = 0;
            Discount = 0;
            PriceWithDiscount = 0;
            Value = 0;
            ProjectID = 0;
            PaymentID = 0;
            PaymentValue = 0;
            PurchasedValue = 0;
            StockQuantity = 0;
            Mode = 1;
            SalesPrice = 0;
            VATPrice = 0;
            ItemTransferFrom = "";
            OverValue = 0;
            OriginalPrice = 0;
            LocationID = 0;
            VisitID = 0;
            IsPrintFiscalInvoice = false;
            IM7Price = 0;
            DoganaValue = 0;
            VATValue = 0;
            AkcizaValue = 0;
            Transport = 0;
            UnitID = 0;
            Coefficient = 0;
            SalesPrice2 = 0;
            CompanyID = 0;
            DepartmentID = 0;
            PDAItemName = "";
            SubOrderID = 0;
            AccountCode = "";
            //ItemLots = GetItemLotsTable();
            LocationID2 = 0;
            Discount3 = 0;
            Points = 0;

        }


        #region Class_Methods


        /// Methods
        /// <summary>
        /// The TransactionID field in the DB
        /// </summary>
        public int TransactionID
        {
            get;
            set;
        }

        /// <summary>
        /// The DetailsType field in the DB
        /// </summary>
        public int DetailsType
        {
            get;
            set;
        }

        /// <summary>
        /// The ItemID field in the DB
        /// </summary>
        public string ItemID
        {
            get;
            set;
        }

        /// <summary>
        /// The ItemName field in the DB
        /// </summary>
        public string ItemName
        {
            get;
            set;
        }

        /// <summary>
        /// The Account field in the DB
        /// </summary>
        public string Account
        {
            get;
            set;
        }

        /// <summary>
        /// The Contracts field in the DB
        /// </summary>
        public string Contracts
        {
            get;
            set;
        }

        /// <summary>
        /// The Quantity field in the DB
        /// </summary>
        public decimal Quantity
        {
            get;
            set;
        }

        /// <summary>
        /// The Price field in the DB
        /// </summary>
        public decimal Price
        {
            get;
            set;
        }

        /// <summary>
        /// The CostPrice field in the DB
        /// </summary>
        public decimal CostPrice
        {
            get;
            set;
        }

        /// <summary>
        /// The Discount field in the DB
        /// </summary>
        public decimal Discount
        {
            get;
            set;
        }

        /// <summary>
        /// The PriceWithDiscount field in the DB
        /// </summary>
        public decimal PriceWithDiscount
        {
            get;
            set;
        }

        /// <summary>
        /// The Value field in the DB
        /// </summary>
        public decimal Value
        {
            get;
            set;
        }

        /// <summary>
        /// The ProjectID field in the DB
        /// </summary>
        public int ProjectID
        {
            get;
            set;
        }

        /// <summary>
        /// The PaymentID field in the DB
        /// </summary>
        public int PaymentID
        {
            get;
            set;
        }

        /// <summary>
        /// The PaymentValue field in the DB
        /// </summary>
        public decimal PaymentValue
        {
            get;
            set;
        }

        /// <summary>
        /// The PurchasedValue field in the DB
        /// </summary>
        public decimal PurchasedValue
        {
            get;
            set;
        }

        /// <summary>
        /// The StockQuantity field in the DB
        /// </summary>
        public decimal StockQuantity
        {
            get;
            set;
        }

        public int Mode { get; set; }

        public decimal SalesPrice { get; set; }
        public decimal VATPrice { get; set; }
        public decimal Points { get; set; }
       
        #endregion
        private DataTable GetItemLotsTable()
        {
            DataTable dtItemLots = new DataTable();
            dtItemLots.TableName="ItemLots";
            DataColumn col = new DataColumn("ID", typeof(int));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("Barcode", typeof(string));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("ItemID", typeof(string));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("Date", typeof(DateTime));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("ExpireDate", typeof(DateTime));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("Memo", typeof(string));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("Quantity", typeof(decimal));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("DetailsID", typeof(int));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("StockLocationID", typeof(int));
            dtItemLots.Columns.Add(col);

            col = new DataColumn("ProductionDate", typeof(DateTime));
            dtItemLots.Columns.Add(col);

            dtItemLots.AcceptChanges();


            return dtItemLots;
        }
        public string ItemTransferFrom { get; set; }
        //public DataTable Numbers { get; set; }
        public decimal OverValue { get; set; }
        public decimal OriginalPrice { get; set; }
        public int LocationID { get; set; }
        public int VisitID { get; set; }

        /// <summary>
        /// The IsPrintFiscalInvoice field in the DB
        /// </summary>
        public bool IsPrintFiscalInvoice
        {
            get;
            set;
        }
        public decimal IM7Price { get; set; }

        public decimal DoganaValue { get; set; }
        public decimal VATValue { get; set; }
        public decimal AkcizaValue { get; set; }
        public decimal Transport { get; set; }
        //public IEnumerator GetEnumerator();
        public int UnitID { get; set; }
        public decimal Coefficient { get; set; }
        public decimal SalesPrice2 { get; set; }

        public int CompanyID { get; set; }
        public int DepartmentID { get; set; }
        public String PDAItemName { get; set; }
        public int SubOrderID { get; set; }
        public decimal Discount2  { get;  set; }
        public string PartnerItremID { get; set; }
        public string AccountCode { get; set; }
        //public DataTable ItemLots { get; set; }
        public int CompensationID { get; set; }
        public int LocationID2 { get; set; }
        public string Barcode { get; set; }
        public string Memo { get; set; }
        public decimal Discount3 { get; set; }
        public int PriceMenuID { get; set; }
        
    }

}