/////////////////////////////////////////////////////////// 
//  Transactions.cs
//  Implementation of the Class Transactions
//  Generated by Gazmend Mehmeti
//  Created on:      05.05.09 6:18:42 PM
//  Original author: Gazmend Mehmeti
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Linq;
using System.Collections;
using FinabitAPI.Core.Global.dto;

namespace FinabitAPI.Finabit.Transaction.dto

{
    public class Transactions : BaseClass
    {

        public Transactions()
        {
            TransactionTypeID = 0;
            TransactionDate = DateTime.Now;
            InvoiceDate = DateTime.Now;
            PartnerName = "";
            DueDate = DateTime.Now;
            TransactionNo = "";
            InvoiceNo = "";
            VAT = true;
            InPL = false;
            PartnerID = 0;
            PartnerName = "";
            PartnersAddress = "";
            PartnersPhoneNo = "";
            PartnersContactPerson = "";
            DepartmentID = 0;
            DriverID = 0;
            PlateNo = "";
            EmpID = 0;
            CashAccount = "";
            Import = false;
            Value = 0;
            VATValue = 0;
            AllValue = 0;
            PaidValue = 0;
            VATPercent = 0;
            VATPercentID = 0;
            Memo = "";
            Reference = "";
            Links = "";
            Active = true;
            JournalStatus = true;
            Transport = 0;
            Dogana = 0;
            Akciza = 0;
            RABAT = 0;
            VatImport = 0;
            DUDNo = "";

            PartnerName = "";
            DepartmentName = "";
            EmployeeName = "";
            TranDetailsColl = new List<TransactionsDetails>();

            ImportValue = 0;
            PaymentMethodID = 0;

            TableID = 0;
            POSStatus = 0;

            TerminID = 0;

            ReferenceID = 0;

            CreateAutomaticRealization = false;
            IsSynchronised = false;

            Commission1 = 0;
            Commission2 = 0;
            Commission3 = 0;
            SuficitAccount = "";
            DeficitAccount = "";
            InternalDepartmentID = 0;
            VehicleID = 0;
            ItemID = "";
            Quantity = 0;
            CurrencyID = 0;
            CurrencyRate = 0;
            OverValue = 0;
            Charges = 0;
            PartnerItemID = "";
            ContractID = 0;
            POSPaid = true;
            HReservationID = 0;
            PaymentTypeID = 0;
            PaymentTypeName = "";
            VisitID = 0;
            PDAInsDate = DateTime.Now;
            CompanyID = 0;
            IsNoCustom = false;
            IncludeTransport = false;
            GenerateJournal = true;
            MinTransactionDate = DateTime.Now;
            AssetID = 0;
            Longitude = 0;
            Latitude = 0;
            PartnerEmail = "";
            Details = new List<TransactionsDetails>();

        }


        #region Class_Methods

        /// Methods
        /// <summary>
        /// The TransactionTypeID field in the DB
        /// </summary>
        public int TransactionTypeID
        {
            get;
            set;
        }

        /// <summary>
        /// The TransactionDate field in the DB
        /// </summary>
        public DateTime TransactionDate
        {
            get;
            set;
        }

        /// <summary>
        /// The InvoiceDate field in the DB
        /// </summary>
        public DateTime InvoiceDate
        {
            get;
            set;
        }

        /// <summary>
        /// The DueDate field in the DB
        /// </summary>
        public DateTime DueDate
        {
            get;
            set;
        }

        /// <summary>
        /// The TransactionNo field in the DB
        /// </summary>
        public string TransactionNo
        {
            get;
            set;
        }

        /// <summary>
        /// The InvoiceNo field in the DB
        /// </summary>
        public string InvoiceNo
        {
            get;
            set;
        }

        /// <summary>
        /// The VAT field in the DB
        /// </summary>
        public bool VAT
        {
            get;
            set;
        }

        /// <summary>
        /// The InPL field in the DB
        /// </summary>
        public bool InPL
        {
            get;
            set;
        }

        /// <summary>
        /// The PartnerID field in the DB
        /// </summary>
        public int PartnerID
        {
            get;
            set;
        }

        /// <summary>
        /// The PartnersAddress field in the DB
        /// </summary>
        public string PartnersAddress
        {
            get;
            set;
        }

        /// <summary>
        /// The PartnersContactPerson field in the DB
        /// </summary>
        public string PartnersContactPerson
        {
            get;
            set;
        }

        /// <summary>
        /// The PartnersPhoneNo field in the DB
        /// </summary>
        public string PartnersPhoneNo
        {
            get;
            set;
        }

        /// <summary>
        /// The DepartmentID field in the DB
        /// </summary>
        public int DepartmentID
        {
            get;
            set;
        }

        /// <summary>
        /// The DriverID field in the DB
        /// </summary>
        public int DriverID
        {
            get;
            set;
        }

        /// <summary>
        /// The PlateNo field in the DB
        /// </summary>
        public string PlateNo
        {
            get;
            set;
        }

        /// <summary>
        /// The EmpID field in the DB
        /// </summary>
        public int EmpID
        {
            get;
            set;
        }

        /// <summary>
        /// The CashAccount field in the DB
        /// </summary>
        public string CashAccount
        {
            get;
            set;
        }

        /// <summary>
        /// The Import field in the DB
        /// </summary>
        public bool Import
        {
            get;
            set;
        }

        /// <summary>
        /// The Value field in the DB
        /// </summary>
        public decimal Value
        {
            get;
            set;
        }

        /// <summary>
        /// The VATValue field in the DB
        /// </summary>
        public decimal VATValue
        {
            get;
            set;
        }

        /// <summary>
        /// The AllValue field in the DB
        /// </summary>
        public decimal AllValue
        {
            get;
            set;
        }

        /// <summary>
        /// The PaidValue field in the DB
        /// </summary>
        public decimal PaidValue
        {
            get;
            set;
        }

        /// <summary>
        /// The VATPercent field in the DB
        /// </summary>
        public decimal VATPercent
        {
            get;
            set;
        }

        /// <summary>
        /// The VATPercentID field in the DB
        /// </summary>
        public int VATPercentID
        {
            get;
            set;
        }

        /// <summary>
        /// The Memo field in the DB
        /// </summary>
        public string Memo
        {
            get;
            set;
        }

        /// <summary>
        /// The Reference field in the DB
        /// </summary>
        public string Reference
        {
            get;
            set;
        }

        /// <summary>
        /// The Links field in the DB
        /// </summary>
        public string Links
        {
            get;
            set;
        }

      
        

        /// <summary> 
      
        /// The Active field in the DB
        /// </summary>
        public bool Active
        {
            get;
            set;
        }

        /// <summary> 

        /// The JournalStatus field in the DB
        /// </summary>
        public bool JournalStatus
        {
            get;
            set;
        }

        /// <summary>
        /// The Transport field in the DB
        /// </summary>
        public decimal Transport
        {
            get;
            set;
        }
        /// <summary>
        /// The Dogana field in the DB
        /// </summary>
        public decimal Dogana
        {
            get;
            set;
        }
        /// <summary>
        /// The Akciza field in the DB
        /// </summary>
        public decimal Akciza
        {
            get;
            set;
        }
        /// <summary>
        /// The RABAT field in the DB
        /// </summary>
        public decimal RABAT
        {
            get;
            set;
        }

        public decimal VatImport { get; set; }
        public string DUDNo { get; set; }
        public string PartnerName { get; set; }
        public string DepartmentName { get; set; }
        public string EmployeeName { get; set; }
        public List<TransactionsDetails> TranDetailsColl { get; set; }
       // public List<TransactionsDetailsExtended> TranDetailsColl2 { get; set; }
        public decimal ImportValue { get; set; }
        public int PaymentMethodID { get; set; }

        public int TableID { get; set; }
        public int POSStatus { get; set; }
        public int TerminID { get; set; }

        public int ReferenceID { get; set; }

        public bool CreateAutomaticRealization { get; set; }

        //public IEnumerator GetEnumerator();

        public bool IsSynchronised {get;set;}


        #endregion

        public int Commission1 { get; set; }
        public int Commission2 { get; set; }
        public int Commission3 { get; set; }

        public string SuficitAccount { get; set; }
        public string DeficitAccount { get; set; }
        public int InternalDepartmentID { get; set; }
        public int VehicleID { get; set; }
        public string ItemID { get; set; }
        public decimal Quantity { get; set; }
        //public DataTable Numbers { get; set; }
        public int CurrencyID { get; set; }
        public decimal CurrencyRate { get; set; }
        public decimal OverValue { get; set; }
        public decimal Charges { get; set; }
        public string PartnerItemID { get; set; }
        public int ContractID { get; set; }
        public bool POSPaid { get; set; }
        public int HReservationID { get; set; }

        public int PaymentTypeID { get; set; }
        public string PaymentTypeName { get; set; }
        public int VisitID { get; set; }
        public DateTime PDAInsDate { get; set; }
        public int CompanyID { get; set; }

        public bool IsNoCustom { get; set; }
        public bool IncludeTransport { get; set; }
        public bool GenerateJournal { get; set; }
        public DateTime MinTransactionDate { get; set; }
        public int AssetID { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public bool BL{get;set; }
        public List<TransactionsDetails> Details = new List<TransactionsDetails>();

        public int ServiceType { get; set; }
        public bool IsPriceFromPartner { get; set; }
        public bool PayValueWithForce { get; set; }

        public int CardID { get; set; }
        public string CardBarcode { get; set; }

        public string PartnerEmail { get; set; }

    }

}